name: 16sseq-workflow
channels:
  - hcc
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - bash-kernel=0.7.1
  - biopython=1.74
  - bleach=3.1.0
  - bzip2=1.0.8
  - ca-certificates=2019.9.11
  - cairo=1.16.0
  - certifi=2019.9.11
  - cython=0.29.13
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.5.0
  - entrypoints=0.3
  - expat=2.2.5
  - fastq-multx=1.3.1
  - fastqc=0.11.8
  - fastx_toolkit=0.0.14
  - font-ttf-dejavu-sans-mono=2.37
  - fontconfig=2.13.1
  - freetype=2.10.0
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - giflib=5.1.7
  - glib=2.58.3
  - gnuplot=5.2.7
  - graphite2=1.3.13
  - harfbuzz=2.4.0
  - icu=64.2
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.4.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=8.0.1
  - libcxx=8.0.1
  - libcxxabi=8.0.1
  - libffi=3.2.1
  - libgd=2.2.5
  - libgtextutils=0.7
  - libiconv=1.15
  - liblapack=3.8.0
  - libllvm8=8.0.1
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.0.10
  - libwebp=1.0.2
  - libxml2=2.9.9
  - llvm-openmp=8.0.1
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - mistune=0.8.4
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - nose=1.3.7
  - notebook=6.0.1
  - nspr=4.20
  - nss=3.46
  - numpy=1.17.2
  - openjdk=11.0.1
  - openssl=1.1.1c
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - pcre=8.41
  - perl=5.26.2
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - pixman=0.38.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - python=3.7.3
  - python-dateutil=2.8.0
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=8.0
  - send2trash=1.5.0
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.2
  - zlib=1.2.11
  - zstd=1.4.0

